In [171]:
import numpy as np

In [172]:
vektor=np.array([1,2,3,4,5])

In [173]:
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [174]:
tensor=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [175]:
vektor , matris ,tensor

(array([1, 2, 3, 4, 5]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],
 
        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]))

In [176]:
import time

In [177]:
z1=time.time()

liste=np.arange(1_000_000)**100

z2=time.time()
print(z2-z1)

0.005981922149658203


In [178]:
vector=np.array([0,1,2,3,4,5,6])

In [179]:
vector[0]

np.int64(0)

In [180]:
vector[5]

np.int64(5)

In [181]:
vector[-1]

np.int64(6)

In [182]:
vector[1:5:1]

array([1, 2, 3, 4])

In [183]:
vector[1:5:2]

array([1, 3])

In [184]:
vector=np.array([1,2,3,4,5,6])
matris=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [185]:
print(vector)

[1 2 3 4 5 6]


In [186]:
print(matris)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [187]:
vector.size

6

In [188]:
matris.size

9

In [189]:
vector.shape

(6,)

In [190]:
matris.shape

(3, 3)

In [191]:
vector.ndim

1

In [192]:
matris.ndim ##boyut

2

In [193]:
vector.dtype  ##veri tipi

dtype('int64')

In [194]:
matris.dtype

dtype('int64')

In [195]:
sayilar=np.array([1,2,3,4,5,6])
sayilar.dtype

dtype('int64')

In [196]:
sayilar=np.array([1,2,3,4,5.0,6])
sayilar=sayilar.astype("int64")
sayilar.dtype

dtype('int64')

In [197]:
sayilar=np.array([1,2,3,4,5,6],dtype="int8")
sayilar.dtype

dtype('int8')

In [198]:
tarih=np.array(["2023-01-01"])
tarih.dtype

dtype('<U10')

In [199]:
tarih.astype("datetime64")

array(['2023-01-01'], dtype='datetime64[D]')

In [200]:
tarih.astype("datetime64[ns]")

array(['2023-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [201]:
matris=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [202]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [203]:
matris[0]

array([1, 2, 3, 4])

In [204]:
matris[1]

array([5, 6, 7, 8])

In [205]:
matris[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [206]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [207]:
matris[0,:]

array([1, 2, 3, 4])

In [208]:
matris[0,:2]

array([1, 2])

In [209]:
matris[0:4,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [210]:
matris[0:4,1:2]

array([[ 2],
       [ 6],
       [10],
       [14]])

In [211]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [212]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [213]:
np.random.randint(0,5)

1

In [214]:
np.random.randint(0,10,(5,5))

array([[1, 1, 6, 9, 2],
       [2, 9, 2, 7, 4],
       [0, 6, 0, 4, 1],
       [4, 9, 6, 1, 3],
       [9, 8, 8, 5, 7]], dtype=int32)

In [215]:
milyon=np.arange(1000000000)

In [216]:
milyon

array([        0,         1,         2, ..., 999999997, 999999998,
       999999999])

In [217]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [218]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [219]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [220]:
np.linspace(0,20,10) ##0ile 20yi 10 eşit aralığa böler

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [221]:
m1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [222]:
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [223]:
m1.shape

(3, 4)

In [224]:
m1.size

12

In [225]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [226]:
m1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [227]:
m1.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [228]:
np.random.randint(0,2,(8,6)).reshape(4,12)

array([[0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1]], dtype=int32)

In [229]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])

In [230]:
matris=np.random.randint(0,5,(4,4))

In [231]:
matris

array([[1, 1, 3, 3],
       [0, 0, 2, 4],
       [1, 1, 1, 4],
       [1, 4, 3, 3]], dtype=int32)

In [232]:
matris2=matris.view()##herhangi bir değişiklişk iksinide etkiler

In [233]:
matris2

array([[1, 1, 3, 3],
       [0, 0, 2, 4],
       [1, 1, 1, 4],
       [1, 4, 3, 3]], dtype=int32)

In [234]:
matris2[0]=[9,9,9,9]

In [235]:
matris

array([[9, 9, 9, 9],
       [0, 0, 2, 4],
       [1, 1, 1, 4],
       [1, 4, 3, 3]], dtype=int32)

In [236]:
matris3=np.random.randint(0,4,(4,4))

In [237]:
matris3

array([[1, 1, 2, 3],
       [3, 0, 1, 3],
       [3, 1, 0, 3],
       [3, 2, 2, 3]], dtype=int32)

In [238]:
matris4=matris3.copy()#matrisler birbirinden etkilenmez

In [239]:
matris4[0]=[0,0,0,0]

In [240]:
matris3

array([[1, 1, 2, 3],
       [3, 0, 1, 3],
       [3, 1, 0, 3],
       [3, 2, 2, 3]], dtype=int32)

In [241]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [243]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [244]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [248]:
np.ones((5,5))
np.ones(shape=(3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [252]:
np.full((4,4),19)

array([[19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19],
       [19, 19, 19, 19]])

In [253]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [256]:
np.eye(5,k=1) ##k köşegeni birim kadar öteleme

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [259]:
np.diag([1,4,1,7,1,1])##köşegenleri belirliyor ve köşegene göre kare matrıs ols

array([[1, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [265]:
r=np.random.randint(0,3,(5,5))
r

array([[1, 1, 0, 2, 0],
       [0, 0, 2, 0, 2],
       [1, 2, 1, 0, 2],
       [1, 1, 0, 0, 1],
       [1, 1, 1, 0, 1]], dtype=int32)

In [268]:
np.diag(r) ## matris prametre olarak verirlirse köşegenlerini dönndürür

array([1, 0, 1, 0, 1], dtype=int32)

In [269]:
np.diag(np.diag(r))

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [275]:
m1=np.ones((5,5)).astype("int64")

In [271]:
m2=np.full((5,5),19)

In [276]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [274]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [277]:
m1*4

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [278]:
m2+3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [279]:
m2+m1

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [280]:
m2-m1

array([[18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18],
       [18, 18, 18, 18, 18]])

In [281]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [282]:
m2/3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [283]:
m2//3##ondalık kısmını almaz

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [284]:
m2%3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [285]:
m3=np.full((5,6),2)

In [286]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [287]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [288]:
m3.shape

(5, 6)

In [289]:
m2.shape

(5, 5)

In [294]:
m3.reshape(30)[:25].reshape(5,5)+m2

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [295]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [297]:
m5=np.arange(5).reshape(5,1)

In [298]:
m5

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [299]:
m1*m5

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])